main: com.occydaboss.skyblock.SkyBlock
name: SkyBlock
version: 0.1b
depend: [FastAsyncWorldEdit, Vault, VoidGenerator]
author: OccyDaBoss
api-version: 1.16
description: Hypixel SkyBlockn't

commands:
  is:
    usage: /<command> [create]
    description: Generates a SkyBlock island.
  forcelevelup:
    usage: /<command>
    description: Levels up the player.
  shop:
    usage: /<command>
    description: Opens the shop menu.
  setlevel:
    usage: /<command> <player> <level>
    description: Sets a player's level.
  levelup:
    usage: /<command>
    description: Opens level GUI.